/**
 * 统一错误码(架构 §10:结构化日志与统一错误码)。
 * 变更需三方评审 — 该文件属于冻结契约的一部分。
 */
export const ERROR_CODES = {
  UNAUTHORIZED: "IAM_401_UNAUTHORIZED",
  TENANT_REQUIRED: "IAM_400_TENANT_REQUIRED",
  RESOURCE_NOT_FOUND: "COMMON_404_RESOURCE_NOT_FOUND",
  VALIDATION_FAILED: "COMMON_400_VALIDATION_FAILED",
  CANVAS_SCHEMA_INVALID: "DESIGN_400_CANVAS_SCHEMA_INVALID",
  JOB_ILLEGAL_TRANSITION: "TASK_409_ILLEGAL_TRANSITION",
  AI_INPUT_INVALID: "AI_400_INPUT_INVALID",
  AI_RESOURCE_EXHAUSTED: "AI_503_RESOURCE_EXHAUSTED",
  AI_MODEL_ERROR: "AI_500_MODEL_ERROR",
  AI_TIMEOUT: "AI_504_TIMEOUT",
  AI_NETWORK_RETRYABLE: "AI_502_NETWORK_RETRYABLE",
  INTERNAL: "COMMON_500_INTERNAL",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export interface ApiError {
  errorCode: ErrorCode;
  message: string;
  traceId: string;
}
