CREATE TABLE IF NOT EXISTS business_generation_records (
    job_id VARCHAR(128) PRIMARY KEY,
    batch_id VARCHAR(64) NULL,
    tenant_id VARCHAR(64) NOT NULL,
    trace_id VARCHAR(64) NOT NULL,
    user_id CHAR(36) NOT NULL,
    user_name_at_event VARCHAR(80) NOT NULL,
    org_unit_id_at_event VARCHAR(64) NULL,
    org_unit_code_at_event VARCHAR(64) NULL,
    org_unit_name_at_event VARCHAR(100) NULL,
    department_id_at_event VARCHAR(64) NULL,
    department_code_at_event VARCHAR(64) NULL,
    department_name_at_event VARCHAR(100) NULL,
    product_id VARCHAR(100) NULL,
    product_name VARCHAR(255) NOT NULL,
    product_code VARCHAR(100) NULL,
    product_view VARCHAR(32) NULL,
    composition_view ENUM('front', 'slight_side') NULL,
    composition_framing ENUM('half_body', 'full_body') NULL,
    generation_mode VARCHAR(40) NULL,
    model_id VARCHAR(100) NULL,
    model_name VARCHAR(255) NULL,
    scene_id VARCHAR(100) NULL,
    scene_name VARCHAR(255) NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'preparing',
    progress INT NOT NULL DEFAULT 0,
    engine VARCHAR(40) NULL,
    error_code VARCHAR(100) NULL,
    error_message VARCHAR(1000) NULL,
    parameters_json JSON NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    INDEX idx_generation_records_user_time (user_id, created_at),
    INDEX idx_generation_records_org_time (org_unit_id_at_event, created_at),
    INDEX idx_generation_records_department_time (department_id_at_event, created_at),
    INDEX idx_generation_records_status_time (status, created_at),
    INDEX idx_generation_records_batch (batch_id),
    UNIQUE KEY uk_generation_records_trace (trace_id),
    CONSTRAINT fk_generation_records_user FOREIGN KEY (user_id) REFERENCES iam_users(id)
);
