CREATE TABLE IF NOT EXISTS business_customers (
    id CHAR(36) PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    customer_name VARCHAR(120) NOT NULL,
    company_name VARCHAR(200) NULL,
    company_short_name VARCHAR(80) NULL,
    remark_id VARCHAR(100) NULL,
    contact_name VARCHAR(80) NULL,
    contact_phone VARCHAR(40) NULL,
    brand_info TEXT NULL,
    industry VARCHAR(100) NULL,
    notes TEXT NULL,
    archive_name VARCHAR(255) NOT NULL,
    archive_name_standard TINYINT(1) NOT NULL DEFAULT 0,
    owner_user_id CHAR(36) NOT NULL,
    owner_user_name_at_create VARCHAR(80) NOT NULL,
    org_unit_id_at_create VARCHAR(64) NULL,
    org_unit_code_at_create VARCHAR(64) NULL,
    org_unit_name_at_create VARCHAR(100) NULL,
    department_id_at_create VARCHAR(64) NULL,
    department_code_at_create VARCHAR(64) NULL,
    department_name_at_create VARCHAR(100) NULL,
    deleted_at DATETIME(3) NULL,
    deleted_by_user_id CHAR(36) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_business_customers_archive (tenant_id, archive_name),
    INDEX idx_business_customers_tenant_time (tenant_id, created_at),
    INDEX idx_business_customers_owner_time (owner_user_id, created_at),
    INDEX idx_business_customers_org_time (org_unit_id_at_create, created_at),
    INDEX idx_business_customers_deleted (tenant_id, deleted_at),
    CONSTRAINT fk_business_customers_owner FOREIGN KEY (owner_user_id) REFERENCES iam_users(id),
    CONSTRAINT fk_business_customers_deleted_by FOREIGN KEY (deleted_by_user_id) REFERENCES iam_users(id)
);
